project:
  type: website

website:
  title: "Calvin J. Chiou"
  favicon: nccu_logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

comments:
  hypothesis: 
    theme: clean
