project:
  type: website

website:
  favicon: /img/nccu_logo.png
  navbar:
    logo: /img/nccu_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume
      - href: research.qmd
        text: Research
  
  page-footer: 
    center: "Website is made with [Quarto](https://quarto.org/), by Calvin Chiou" 
    

format:
  html:
    theme:
      light: [sandstone, theme-light.scss]
      dark: [sandstone, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

comments:
  hypothesis: 
    theme: clean

