project:
  type: website
  output-dir: docs

website:
  title: "Calvin J. Chiou"
  favicon: nccu_logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research
<<<<<<< Updated upstream
=======
      - href: resources.qmd
        text: Resources
  
  page-footer: 
    center: "Website is made with [Quarto](https://quarto.org/), by Calvin Chiou" 
    
>>>>>>> Stashed changes

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

comments:
  hypothesis: 
    theme: clean
