project:
  type: website

website:
  favicon: /img/nccu_logo.png
  navbar:
    logo: /img/nccu_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: resources.qmd
        text: Resources
  
  page-footer: 
    right: "This website is built with [Quarto](https://quarto.org/)"
    

format:
  html:
    theme:
      light: sandstone
      dark: [sandstone, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

comments:
  hypothesis: 
    theme: clean

