project:
  type: website
  output-dir: docs
  
# Metadata stuff
pagetitle: "{{< meta title >}} | Calvin J. Chiou"
author-meta: "Calvin J. Chiou"

website:
  title: "Calvin Chiou | NCCU College of Commerce"
  # site-url: "https://calvinchiou.com"
  favicon: /img/nccu_logo.png
  navbar:
    pinned: true
    title: false
    logo: /img/nccu_logo.png
    
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: resources.qmd
        text: Resources
    
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/calvinchiou1992/
      - icon: github
        href: https://github.com/calvinchiou
      - icon: envelope
        href: "mailto:jjchiou@nccu.edu.tw"
        # https://jpswalsh.github.io/academicons/
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com.tw/citations?user=WvORrXMAAAAJ&hl=en
  
  page-footer: 
    left: |
      {{< fa brands creative-commons >}} {{< var years >}}  Calvin J. Chiou \
      All content licensed under [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    
    right: "This website is made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)"
      
    border: true
  
  back-to-top-navigation: true
  bread-crumbs: false
  
  google-analytics: "G-8KXQZ8LK16"
    
# theme can refer https://quarto.org/docs/output-formats/html-themes.html
format:
  html:
    theme:
      light: [sandstone, theme-light.scss]
      dark: [sandstone, theme-dark.scss]
    mainfont: "Roboto"
    highlight-style: monokai
    respect-user-color-scheme: false
    # fontsize: normal
    # mainfont: "Gill Sans, sans-serif"
    # css: styles.css
    toc: true
    footnotes-hover: true
    grid:
      body-width: 1200px
    # fig-cap-location: margin
    # reference-location: margin
    # grid:
    #   sidebar-width: 300px
    #   body-width: 1250px
    #   margin-width: 450px
    #   gutter-width: 2.0rem
    
    include-in-header:
      text: |
        <script src="https://cdn.lordicon.com/lordicon.js"></script>
    
    include-after-body:
    - text: |
        <script>
          document.addEventListener("DOMContentLoaded", function () {
            const links = document.querySelectorAll("a[href]");
            links.forEach(function (link) {
              const href = link.getAttribute("href");
              if (
                href &&
                !href.startsWith("/") &&
                !href.startsWith("#") &&
                !href.startsWith(window.location.origin) &&
                !href.includes(window.location.hostname)
              ) {
                link.setAttribute("target", "_blank");
                link.setAttribute("rel", "noopener noreferrer");
              }
            });
          });
        </script>
editor: visual


