---
title: "About me"
table-of-contents: true
about:
  template: marquee
---

<lord-icon src='https://cdn.lordicon.com/shcfcebj.json' trigger='loop' state='hover-nodding' delay='1500' colors='primary:#121331,secondary:#3080e8' style='width:60px;height:60px'></lord-icon>

[Download my CV (PDF in a new tab ↗)](files/CV_calvinchiou.pdf){target="_blank" rel="noopener"}

## Employment

National Chengchi University \| Assistant Professor \| Feb 2024 - present

## Research Interests

Innovation, Institutional Investors, Corporate Governance, Empirical Corporate Finance, Behavioral Finance

## Education

PhD in Finance \| Nanyang Technological University \| 2019-2024

- Visiting Researcher \| National University of Singapore \| 2019

MS in Finance \| National Central University \| Taiwan \| 2017

BBA in Finance and Cooperative Management \| National Taipei University \| Taiwan \| 2015

## Grants

Off-Site to UT Austin EMI Professional Development Program, *National Taiwan Normal University & UT Austin* \| 2025

Grants for New Faculty Members to Apply to NSTC Academic Research, *NCCU* \| 2024

Co-Principal Investigator (with [Hao-Chang Sung](https://busadm.ccu.edu.tw/p/405-1248-31599,c3236.php?Lang=zh-tw)). "The Impact of External Oversight on the Effectiveness of Executive Compensation Clawback Enforcement: Theoretical and Empirical Evidence." *National Science and Technology Council (NSTC)*, 2025-2027, \$NTD 1,758,000

Principal Investigator. "Interwoven Influence: Essays on Board Interlocks in Corporate Governance." *National Science and Technology Council (NSTC)*, 2024-2026, \$NTD 1,378,000

## Awards and Honors

Fubon Best Paper Award \| 2024

Excellent Undergraduate English-taught Course Award, NCCU \| 2024

Taiwanese Government Scholarship to Study Abroad \| 2022 - 2023

NTU Research Scholarship \| 2019 - 2023

Best Paper Award, TSC Thesis Symposium \| 2017

Shanghai Commercial & Savings Bank Scholarship \| 2017

## Professional Services

**Journal Referee**: *Pacific-Basin Finance Journal(x3), British Accounting Review, Finance Research Letters(x2), Emerging Markets Finance and Trade(x2), Review of Securities and Futures Markets, Journal of Social Sciences and Philosophy, Journal of Management and Business Research*

**Conference Referee**: *AFAANZ*

## Presentations

2025: International Conference of TFA[^1], International Conference for FeAT[^2], AsianFA Annual Conference, AFAANZ Annual Conference, Annual Conference for Taiwan Econometric Society (scheduled), National Chengchi University

[^1]: Taiwan Financie Association (TFA), <https://www.finance.org.tw/fnhome>

[^2]: Financial Engineering Association of Taiwan (FeAT), <http://www.feat.org.tw/>

2024: International Conference of TFA, Frontier in Accounting and Finance International Conference, INFORMS Annual Meeting, Sydney Banking and Financial Stability Conference (SBFC), Chang Gung University, National Central University, National Chengchi University

2023: International Conference of TFA, National Kaohsiung University of Science and Technology, National Taipei University

2022: National Chengchi University, National Central University, National Taipei University

2021: Cross Country Perspectives in Finance (CCPF), CCPF-JIFMIM Symposium, International Conference of TFA

2018: AsianFA Annual Conference$^*$

2017: International Conference of TFA$^\dagger$, TFA Conference on Asset Pricing$^*$, Conference on the Theories and Practices of Securities and Financial Markets$^*$

($^*$ Presented by Coauthor, $^\dagger$ Discussant)

## Selected Certificates

Data Analysis with R Specialization, Duke University \| [Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/HZ6WHJQG3TSW)

Google Data Analytics Specialization, Google \| [Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/9T2PRT75NGR3)

Applied Text Mining in Python, University of Michigan \| [Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/PVT7B574ACNF)

Fundamentals of Machine Learning in Finance, New York University \| [Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/N4LWW7YT4W37)

## Programming

R, Python, Stata, SAS, $\LaTeX$

## Language

English (fluent), Mandarin (native)