---
title: "Recommendation Letter Policy"
---

If you are considering asking for a recommendation letter, please read this policy carefully. The best way to approach a professor is to ask, “Would you be able to write me a **strong** recommendation letter?” This gives the professor (not necessarily me) the opportunity to reflect on your performance and provide an honest answer. Always **waive your right** to view the letter to ensure its credibility unless the professor explicitly advises otherwise. Whenever possible, please **schedule an in-person meeting** before making a formal request.

## Who is Eligible?

-   Students who have received A+ or exceptional performance in at least one of my courses.
-   Master’s or PhD students under my supervision.
-   NSTC Undergraduate Research Project under my supervision.
-   My research assistants.

## Annual Limit

-   I will write **no more than 4 recommendation letters** per academic year.
-   At least **1 slot** is reserved for PhD or research-focused master’s program applications.
-   This limit is set to preserve the strength and credibility of my letters.

## Request Deadline

-   Please contact me at least **TWO** months before your application deadline.

## Information Required

-   Your CV
-   Your transcript
-   A list of target programs
-   Your statement of purpose (SOP) for your top choice program
-   Any additional materials you wish me to reference in the letter
