---
title: "Common Ownership Network and Board Gender Diversity"
description: "*Working Paper*"
author: "Calvin J. Chiou"
date: "Jan 12, 2025"
categories:
  - Working Papers
---

## Abstract

This study investigates the potential of common ownership to expand the pool of female director candidates and alleviate the underrepresentation of women on corporate boards. By measuring the fraction of female directors from peer firms sharing the same blockholder as the focal firm, I proxy the potential supply of female directors. The baseline results indicate a positive correlation between the supply of female directors in peer firms and the representation of women in the focal firm, as well as an increased likelihood of new female director appointments. In addition, these firms show an increased likelihood of women attaining leadership positions on board committees. Using the California Senate Bill No. 826 and peer female director appointments as quasi-experimental settings, the difference-in-difference-in-differences (DDD) analysis shows that firms under common ownership narrow the gap between the current and mandated numbers of female directors. The results remain robust in accounting for the activeness of the Big Three and underscore the network effect of common ownership on the supply side of the labor market for female directors.

## Keywords

*Board gender diversity, common ownership, gender quota, institutional investors, corporate governance*

## Award

-   Fubon Best Paper Award, Jun 2024.

## Conference

-   Sydney Banking and Financial Stability Conference, Sydney, Australia, Dec 2024.

-   2024 NTU Winter Workshop on Entrepreneurship, Taipei, Taiwan, Dec 2024.

-   INFORMS Annual Meeting, Seattle, USA, Oct 2024.

-   International Conference of Taiwan Finance Association (TFA), Kaohsiung, Taiwan, Jun 2024.

-   Frontier in Accounting and Finance International Conference, Taipei, Taiwan, Apr 2024.
