---
title: "The Impact of Environmental Performance on Financial Performance and Stock Returns - Evidence from Listed Companies in Taiwan"
description: "*R&R at Journal of Financial Studies* (TSSCI)"
author: "Calvin J. Chiou, Tsung-Hsuan Li, Chang Chan, and Chun-Kuei Hsieh"
date: "June 1, 2024"
categories:
  - Working Papers
---

## Abstract

This paper examines the impact of a firm's environmental performance on its financial performance and stock return. We refer to the methods of Lins et al. (2017) and Chen et al. (2018) and use the data of the Taiwan Sustainability Rating for listed companies and OTC companies that have issued sustainability reports of the previous year from 2016 to 2021. The findings include: (1) For the manufacturing industry, environmental performance has a significant positive correlation with financial performance and stock returns. (2) For the electronics industry, environmental performance has a significant negative correlation with financial performance and has no correlation with stock returns. However, there is a significant positive correlation between economic performance and stock returns. (3) As far as the service industry and the financial industry are concerned, environmental performance has no significant relationship with financial performance and stock returns; however, the social performance of the service industry and the economic performance of the financial industry have a significant positive relationship with financial performance and stock returns. The above findings imply that, for the listed companies and OTC companies in Taiwan, the impact of environmental performance on financial performance and stock returns is not only related to the degree of government and public attention to the environmental issues in the industry to which the company belongs, but also related to the closeness of the industry's connection with the international supply chain.

## Keywords

*Sustainability Report, CSR, ESG, Taiwan Sustainability Ratings, Financial Performance, Stock Returns*

## Conference

-   International Conference of Taiwan Finance Association (TFA), Taichung, Taiwan, Jun 2023.
