---
title: "Corporate Social Performance, Retail Investor Trading, and Stock Price Crash Risk"
description: "*R&R at Finance Research Letters*"
author: 
  - name: "Chang Chan"
    affiliations:
      - name: "Dharma Drum Institute of Liberal Arts"
  - name: "**Calvin J. Chiou**"
    affiliations:
      - name: "National Chengchi University, College of Commerce"
  - name: "Chin-En Wu"
    affiliations:
      - name: "Drexel University, LeBow College of Business"
    attributes:
      corresponding: true
date: "Feb, 2026"
categories:
  - Working Papers
---

## Abstract

We investigate the relationship between corporate social performance (CSP) and stock price crash risk in Taiwan, a market dominated by retail investors. Using firm-level data from the Taiwan Sustainability Ratings, we find that higher CSP is associated with lower crash risk. Employing a dynamic system GMM estimator and a two-stage Heckman selection model, we show that this relationship is robust to endogeneity concerns. Importantly, the negative association between CSP and crash risk is significantly stronger among firms with higher retail trading intensity. This evidence suggests that in retail-dominated markets, CSP is more strongly associated with stock price stability when retail trading intensity is high. Our findings highlight that the association between corporate social performance and crash risk depends on investor composition, indicating that improvements in firms’ information environments are more strongly reflected in prices when retail participation is greater.

## Keywords

*Corporate social performance, Stock crash risk, Retail attention*
