---
title: "When Black Swan Meets Green Swan: ESG Engagement and Financial Resilience in U.S. Airlines during COVID-19"
description: "*Under Submission*"
author: 
  - name: "Hui-Chieh Chen"
    affiliations:
      - name: "National Chung Cheng University"
  - name: "**Calvin J. Chiou**"
    affiliations:
      - name: "National Chengchi University"
  - name: "Yueh-Neng Lin"
    affiliations:
      - name: "National Chung Hsing University"
    attributes:
      corresponding: true
date: "May, 2025"
categories:
  - Working Papers
---

## Abstract

It is a challenge for firms to survive the combination of black and green swans, especially during the COVID-19 pandemic. With the airline industry as our target laboratory, we investigate the commitment to ESG of firms and its effects during this black-swan period. We find that airline companies who have implemented sustainable aviation fuels (SAF) experienced better operating performance during the pandemic. Companies with greater financial pressure are found to allocate less resources to ESG when passenger numbers plummet. Overall, the worsening financial situation resulting from the black swan does not significantly decrease the attention given to green swan initiatives.

## Keywords

*Sustainability, COVID-19 pandemic*

## Conference

-   International Conference of Taiwan Finance Association (TFA), Taichung, Taiwan, Jun 2023.
