---
title: "The impact of mandatory corporate social responsibility reporting on liquidity and risk"
description: "*Journal of Accounting Review (會計評論)*, Vol. 72, 35-82 (TSSCI)"
author: 
  - name: "Chang Chan"
    affiliations: "National Taipei University"
  - name: "Chao-Hung Huang"
    affiliations: "National Chengchi University"
  - name: "**Calvin J. Chiou**"
    affiliations: "National Chengchi University"
  - name: "Wen-Chyan Ke"
    affiliations: "National Taipei University"
date: "January 2021"
doi: DOI:10.6552/JOAR.202101_(72).0002
categories:
  - Publications
---

# Abstract

This study investigates whether mandatory corporate social responsibility (CSR) reporting ameliorates liquidity and reduces risk for stocks. Moreover, we explore whether these impacts vary with regulated company category and stakeholder influence capacity. For a mandatory CSR reporting regulation in Taiwan, we assess the policy’s effects using difference-in-differences (DID) modeling. The results show that mandatory CSR reporting significantly increases liquidity and reduces idiosyncratic risks. However, the effect on systematic risk is asymmetric—a high (low) systematic risk is accompanied by a positive (negative) market return; namely, a large (small) price increase (decrease) caused by a positive (negative) market return. This aligns with the insurance-like benefits argument. These findings suggest investors hold on to CSR firms because of increased information transparency and good financial performance during a recession. The improved liquidity is more significant for firms in the electronics and chemical industries and for firms with a large equity share owned by domestic institutional investors. Idiosyncratic risk is reduced more for the latter two. The findings provide feedback on mandatory CSR reporting to policy makers and provide reference for firms and investors.

## Keywords

*Corporate social responsibility, Liquidity, Systematic risk, Non-systematic risk.*

## Conference

-   International Conference for Financial Engineering Association of Taiwan (FeAT), Taoyuan, 2017.

-   Frontier in Accounting and Finance International Conference, Taipei, Taiwan, 2019.
